<?php

/**
 * Interfaz de los controladores
 */
require_once "controller/controller.Generico.php";
/**
 * Contiene los metodos que realizan las operaciones necesarias en la tabla categoria
 */
require_once "model/Categoria.php";
/**
 * Contiene los metodos que realizan las operaciones necesarias en la tabla comentario
 */
require_once "model/Comentario.php";
/**
 * Contiene los metodos que realizan las operaciones necesarias en la tabla episodio
 */
require_once "model/Episodio.php";
/**
 * Contiene los metodos que realizan las operaciones necesarias en la tabla puntuacion
 */
require_once "model/Puntuacion.php";
/**
 * Contiene los metodos que realizan las operaciones necesarias en la tabla seropel
 */
require_once "model/Seropel.php";
/**
 * Contiene los metodos que realizan las operaciones necesarias en la tabla usuario
 */
require_once "model/Usuario.php";
/**
 * Controla la Sesión
 */
require_once "model/Sesion.php";
