<footer class="dark-wrapper inverse-text">
    <div class="container inner">
        <div class="row d-md-flex align-items-md-center">
            <div class="col-md-6 text-center text-md-left">
                <a title="lgpl" href="LICENSE.md" style="margin: 10px;"><img src="assets/images/lgpl.png" height="50" alt="lgpl" /></a>
                <a title="GitHub" href="https://github.com/tmssnchzprds/SYP" style="margin: 10px;"><img src="assets/images/github.png" height="50" alt="GitHub" /></a>
                <a title="Prezi" href="https://prezi.com/view/SLOsetk4lAvQjdhXQpGf/" style="margin: 10px;"><img src="assets/images/prezi.png" height="50" alt="Prezi" /></a>
                <h6 class="mb-0" style="margin: 10px;">Este proyecto ha sido realizado por Tómas Sánchez Paredes.</h6>
            </div>
            <!--/column -->
            <div class="col-md-2 text-center">
                <a title="phpdoc" href="documentacion/phpdoc" style="margin: 10px;"><img src="assets/images/phpdocumentor.png" height="100" alt="phpdocumentor" /><h3>Documentacion</h3></a>
            </div>
            <div class="col-md-2 text-center">
                <a title="Manual de Usuario" href="documentacion/manual-usuario.pdf"><img src="assets/images/pdf.png" height="50" alt="Manual de Usuario" /><h3>Manual de Usuario</h3></a>
            </div>
            <div class="col-md-2 text-center">
                <a title="Manual Tecnico" href="documentacion/manual-tecnico.pdf"><img src="assets/images/pdf.png" height="50" alt="Manual Tecnico" /><h3>Manual Técnico</h3></a>
            </div>
            <!--/column -->
            <!--/column -->
        </div>
        <!--/.row -->
    </div>
    <!-- /.container -->
</footer>
