    <footer class="dark-wrapper inverse-text">
      <div class="container inner">
        <div class="row d-md-flex align-items-md-center">
          <div class="col-md-6 text-center text-md-left">
            <p class="mb-0">© 2022 . Todos los derechos reservados.</p>
            <p class="mb-0">Este proyecto ha sido realizado por Tómas Sánchez Paredes.</p>
          </div>
          <!--/column -->
          <div class="col-md-2 text-center"></div>
          <!--/column -->
          <!--/column -->
        </div>
        <!--/.row -->
      </div>
      <!-- /.container -->
    </footer>
