  <script src="assets/js/jquery.min.js"></script>
  <script src="assets/js/popper.min.js"></script>
  <script src="assets/js/bootstrap.min.js"></script>
  <script src="assets/revolution/js/jquery.themepunch.tools.min.js"></script>
  <script src="assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
  <script src="assets/js/plugins.js"></script>
  <script src="assets/js/scripts.js"></script>
  <script src="assets/js/myscripts.js"></script>