  <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="assets/css/plugins.css">
  <link rel="stylesheet" type="text/css" href="assets/revolution/css/settings.css">
  <link rel="stylesheet" type="text/css" href="assets/revolution/css/layers.css">
  <link rel="stylesheet" type="text/css" href="assets/revolution/css/navigation.css">
  <link rel="stylesheet" type="text/css" href="assets/fonts/icons.css">
  <link rel="stylesheet" type="text/css" href="assets/css/style.css">
  <link rel="stylesheet" type="text/css" href="assets/css/color/lavender.css">