<link rel="icon" href="assets/img/favicon.png">
<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="assets/css/plugins.css">
<link rel="stylesheet" type="text/css" href="assets/fonts/icons.css">
<link rel="stylesheet" type="text/css" href="assets/css/style.css">
<link rel="stylesheet" type="text/css" href="assets/css/color/orange.css">